export const BUTTONS = {
  SAVE: "Guardar",
  SAVE_CHANGES: "Guardar Cambios",
  CANCEL: "Cancelar",
  DELETE: "Eliminar",
  CONFIRM_DELETE: "Sí, eliminar",
  DELETING: "Eliminando...",
  SAVING: "Guardando...",
  CREATING: "Creando...",
  EDIT: "Editar",
  CLOSE: "Cerrar",
  LOGOUT: "Cerrar Sesión",
  CONTINUE: "Continuar",
  BACK_HOME: "Volver al Inicio",
  RESEND_EMAIL: "Reenviar correo de verificación",
  SENDING: "Enviando...",
  UPDATING: "Actualizando...",
  UPDATE_PASSWORD: "Actualizar Contraseña",
  CREATE_JOB: "Crear Vacante",
  INVITE_CANDIDATE: "Invitar Candidato",
  ASSIGN_CANDIDATE: "Asignar Candidato",
  PREVIOUS: "Anterior",
  NEXT: "Siguiente",
  LOADING: "Cargando...",
  VERIFYING: "Verificando...",
  GO_TO_DASHBOARD: "Continuar al Dashboard",
  LOGIN: "Iniciar Sesión",
  REGISTER: "Registrarse",
  LOGGING_IN: "Ingresando...",
  LOGIN_SUBMIT: "Ingresar",
  CREATING_ACCOUNT: "Creando cuenta...",
  CREATE_ACCOUNT: "Crear Cuenta",
  ADD_QUESTION: "Agregar Pregunta",
  CREATE_FIRST_JOB: "Crear Primera Vacante",
  ASSIGN_BY_DOC: "Asignar por Documento",
  SEARCH_JOBS: "Buscar trabajos",
  EXPLORE_JOBS: "Explorar Vacantes",
  VIEW_JOB: "Ver Vacante",
  SAVE_CONTINUE: "Guardar y Continuar",
  RESEND: "Reenviar",
  VIEW_ANALYSIS: "Ver Análisis",
  BACK_DASHBOARD: "Volver al Panel",
  EXIT: "Salir",
  RETRY: "Reintentar",
  RETRY_CONNECTION: "Reintentar Conexión",
  ENABLE_MIC: "Habilitar Micrófono",
  CONTINUE_INTERVIEW: "Continuar Entrevista",
  START_INTERVIEW: "Realizar Entrevista",
  FINISH: "Finalizar",
  VIEW_DETAILS: "Ver detalles",
  DOWNLOAD_PDF: "Descargar Informe (PDF)",
  INVITING: "Invitando...",
  SEND_INVITATION: "Enviar Invitación",
  SEND_RESET_LINK: "Enviar Enlace de Recuperación",
  TRY_ANOTHER_EMAIL: "Intentar con otro correo",
  EXPORT: "Exportar",
  ADD_REQUIREMENT: "Agregar Requisito"
} as const;

export const TITLES = {
  COMPANY_DASHBOARD: "Panel de Empresa",
  JOB_DETAILS: "Detalles de la Vacante",
  CREATE_JOB: "Nueva Vacante",
  EDIT_JOB: "Editar Vacante",
  DELETE_JOB_CONFIRM: "¿Eliminar vacante?",
  VERIFY_EMAIL: "Verificación Pendiente",
  VERIFIED: "¡Verificado!",
  ERROR: "Error",
  WELCOME_BACK: "✅ ¡Bienvenido de vuelta!",
  REGISTRATION_SUCCESS: "🎉 ¡Registro exitoso!",
  EMAIL_ALREADY_REGISTERED: "Email ya registrado",
  VERIFICATION_REQUIRED: "Verificación requerida",
  LOGIN_ERROR: "Error al iniciar sesión",
  ACTION_NOT_ALLOWED: "Acción no permitida",
  PASSWORDS_DO_NOT_MATCH: "Las contraseñas no coinciden",
  REGISTRATION_ERROR: "Error en el registro",
  COMPANY_LOGIN: "Acceso para Empresas",
  ADMIN_LOGIN: "Acceso Administrativo",
  CANDIDATE_LOGIN: "Acceso para Candidatos",
  RECENT_JOBS: "Vacantes Recientes",
  RECENT_ACTIVITY: "Actividad Reciente",
  PROFILE_ERROR: "Error de Perfil",
  JOB_CREATED_SUCCESS: "✅ Vacante creada exitosamente",
  JOB_UPDATED_SUCCESS: "✅ Vacante actualizada",
  JOB_DELETED_SUCCESS: "🗑️ Vacante eliminada",
  CREATE_JOB_ERROR: "Error al crear la vacante",
  CANDIDATE_DASHBOARD: "Panel del Candidato",
  MY_APPLICATIONS: "Mis Postulaciones",
  YOUR_INFO: "Tu Información",
  SCHEDULE: "Agenda",
  COMPLETE_PROFILE: "Completa tu Perfil",
  NOT_IMPLEMENTED: "Función no implementada",
  COMPANY_SETUP: "Configura tu Empresa",
  COMPANY_CREATED_SUCCESS: "¡Empresa Creada!",
  INTERVIEW_COMPLETED: "¡Entrevista Completada!",
  ACCESS_ERROR: "Error de Acceso",
  EVALUATION_INTERVIEW: "Entrevista de Evaluación",
  PROCESS_FINISHED: "Proceso Finalizado",
  INVITATION_RECEIVED: "¡Invitación Recibida!",
  WAITING_INVITATION: "A la espera de invitación",
  TRANSCRIPT: "Transcripción de la Entrevista",
  REPORT_UNAVAILABLE: "Informe no disponible",
  PERFORMANCE_REPORT: "Informe de Rendimiento",
  KEY_METRICS: "Métricas Clave",
  RECORDING: "Grabación",
  INVITE_CANDIDATE: "Invitar Candidato",
  FORGOT_PASSWORD: "Recuperar Contraseña",
  NEW_PASSWORD: "Nueva Contraseña",
  SUCCESS: "¡Éxito!",
  EMAIL_SENT_TITLE: "¡Correo Enviado!",
  ADMIN_PANEL: "Admin Panel",
  ACCESS_DENIED: "Acceso denegado",
  PLATFORM_SUMMARY: "Resumen de la Plataforma",
  USER_MANAGEMENT: "Gestión de Usuarios",
  CONFIRM_DELETE_USER: "¿Estás seguro?",
  COMPANY_MANAGEMENT: "Gestión de Empresas",
  CANDIDATE_MANAGEMENT: "Gestión de Candidatos",
  INTERVIEW_MANAGEMENT: "Gestión de Entrevistas",
  COMING_SOON: "Próximamente",
  GENERAL_SETTINGS: "Ajustes Generales",
  RETAIL_PARAMS: "Parámetros de Retail",
  FEATURE_IN_DEVELOPMENT: "Funcionalidad en Desarrollo",
  EMAIL_TEMPLATE_MGMT: "Gestión de Plantillas de Email",
  CHANGE_PASSWORD: "Cambiar Contraseña",
  CHANGE_PASSWORD_ERROR: "Error al cambiar la contraseña",
  PERMISSION_DENIED: "Permiso Denegado",
  AUDIO_SETUP: "Configuración de Audio",
  TOP_APPLICANTS: "Top 5 Postulantes",
  COMPARATIVE_ANALYSIS: "Análisis Comparativo",
  METRIC_COMPARISON: "Comparación de Métricas",
  LIVE_TRANSCRIPTION: "Transcripción en Vivo",
  CONNECTION_DETAILS: "Detalles de la Conexión",
  FEEDBACK_GENERAL: "Feedback General",
  QUESTIONS_BREAKDOWN: "Desglose de Preguntas",
  STRENGTHS: "Fortalezas",
  AREAS_FOR_IMPROVEMENT: "Áreas de Mejora",
  COMMUNICATION_QUALITY: "Calidad de Comunicación",
  SUGGESTED_NEXT_STEPS: "Siguientes Pasos Sugeridos",
  FULL_TRANSCRIPT: "Transcripción Completa",
  INTERVIEWER_AI: "Entrevistador (IA)",
  CANDIDATE: "Candidato",
  INTERVIEWER_NAME: "Jennifer",
  APPROVE_CANDIDATE_CONFIRM: "¿Aprobar candidato?",
  REJECT_CANDIDATE_CONFIRM: "¿Rechazar candidato?",
  INTERVIEW_RECORDING: "Grabación de Entrevista",
  PLATFORM_VERSION: "v1.1",
  YOU: "Tú",
  AI_ADVISOR: "Jennifer",
  CONGRATULATIONS: "¡Felicidades!",
  PLATFORM_NAME: "Conecta"
} as const;

export const MESSAGES = {
  CONFIRM_DELETE_JOB:
    "Esta acción no se puede deshacer. Se eliminará permanentemente la vacante y todas las aplicaciones asociadas.",
  GENERIC_ERROR: "Ocurrió un error. Por favor intenta de nuevo.",
  SESSION_EXPIRED: "Tu sesión ha expirado.",
  JOB_CREATED: "Vacante creada exitosamente.",
  JOB_UPDATED: "Vacante actualizada exitosamente.",
  JOB_DELETED: "Vacante eliminada exitosamente.",
  EMAIL_VERIFIED: "¡Tu correo ha sido verificado correctamente!",
  EMAIL_INVALID_LINK: "El enlace de verificación es inválido o ha expirado.",
  EMAIL_SENT: "Correo enviado.",
  CHECK_EMAIL: "Revisa tu correo para verificar tu cuenta.",
  UNVERIFIED_ACCOUNT: "Tu cuenta aún no ha sido verificada.",
  VERIFYING_EMAIL_MSG: "Verificando tu correo electrónico...",
  ALREADY_VERIFIED_MSG: "Tu cuenta ya está verificada.",
  LOGIN_TO_VERIFY: "Debes iniciar sesión para verificar tu cuenta.",
  RESEND_ERROR: "No se pudo enviar el correo.",
  RESEND_SUCCESS: "Se ha enviado un nuevo enlace de verificación a tu correo.",
  USER_INFO_ERROR: "No se pudo obtener la información del usuario.",
  NO_TOKEN_ERROR:
    "No se encontró el token de verificación. Por favor contacta soporte.",
  NO_EMAIL_ERROR:
    "No se pudo determinar tu correo electrónico. Por favor inicia sesión.",
  VERIFICATION_PENDING_MSG:
    "Tu cuenta aún no ha sido verificada. Por favor, revisa tu correo electrónico para encontrar el enlace de verificación.",
  LOGIN_SUCCESS: "Has iniciado sesión correctamente.",
  REGISTRATION_SUCCESS_MSG:
    "Revisa tu correo para verificar tu cuenta. Serás redirigido a la página de verificación.",
  EMAIL_ALREADY_REGISTERED_MSG:
    "Este email ya está registrado. Por favor, inicia sesión.",
  VERIFY_EMAIL_REQUIRED:
    "Por favor, verifica tu correo electrónico para continuar.",
  INVALID_CREDENTIALS: "Credenciales incorrectas",
  ADMIN_REGISTER_ERROR:
    "No puedes registrar el correo del administrador. Por favor, inicia sesión.",
  PASSWORDS_MISMATCH: "Por favor verifica que ambas contraseñas sean iguales.",
  SOMETHING_WENT_WRONG: "Algo salió mal",
  SKILL_HELP:
    "Escribe para buscar skills existentes o crear nuevas. Presiona Enter para agregar.",
  NO_JOBS: "No tienes vacantes creadas",
  NO_CANDIDATE_ACTIVITY: "No hay actividad reciente de candidatos.",
  ERROR_LOADING_USERS: "No se pudieron cargar los usuarios.",
  ERROR_DELETING_USER: "No se pudo eliminar al usuario.",
  USER_DELETED: "Usuario eliminado.",
  DELETE_USER_WARNING:
    "Esta acción es irreversible. Se eliminará permanentemente al usuario y todos sus datos asociados (vacantes, aplicaciones, etc.).",
  CONFIRM_DELETE_USER_BTN: "Sí, eliminar usuario",
  ANALYTICS_COMING_SOON: "Las analíticas están en camino",
  COME_BACK_SOON: "¡Vuelve pronto!",
  ERROR_FETCHING_DATA: "No se pudieron cargar los datos",
  ERROR_CREATING_JOB:
    "No se pudo crear la vacante. Verifica tu perfil y vuelve a intentarlo.",
  ERROR_UPDATING_JOB: "No se pudo actualizar la vacante",
  ERROR_DELETING_JOB: "No se pudo eliminar la vacante",
  JOB_CREATED_DESC:
    "Tu oferta de trabajo está activa y lista para recibir candidatos.",
  JOB_UPDATED_DESC: "Los cambios han sido guardados.",
  JOB_DELETED_DESC: "La vacante y sus aplicaciones han sido eliminadas.",
  TITLE_MIN_LENGTH: "El título debe tener al menos 3 caracteres",
  DESC_MIN_LENGTH: "La descripción debe tener al menos 50 caracteres",
  INVALID_CONTRACT_TYPE: "Tipo de contrato inválido",
  INVALID_SALARY: "Salario mínimo inválido",
  MAX_SALARY_ERROR: "El salario máximo debe ser mayor al mínimo",
  INVALID_CURRENCY: "Moneda inválida",
  REQUIREMENT_NEEDED: "Debes agregar al menos un requisito",
  WELCOME: "Bienvenido,",
  CHECKING_PROFILE: "Verificando perfil de empresa...",
  INTERVIEW_COMPLETED: "Entrevista completada.",
  CANDIDATE_APPROVED: "Candidato aprobado correctamente.",
  CANDIDATE_REJECTED: "Candidato rechazado.",
  ERROR_UPDATING_STATUS: "No se pudo actualizar el estado del candidato.",
  INTERVIEW_FLEXIBLE: "Entrevista flexible, sin fecha agendada.",
  INTERVIEW_PAST: "La hora de la entrevista ha pasado",
  STARTS_PREFIX: "Comienza en",
  DAYS_UNIT: "días",
  HOURS_UNIT: "horas",
  STARTS_SOON: "Comienza pronto",
  NO_APPLICATIONS: "No tienes postulaciones",
  NO_APPLICATIONS_DESC: "Cuando postules a un trabajo, aparecerá aquí.",
  WELCOME_DASHBOARD: "Bienvenido a tu panel",
  DASHBOARD_DESC:
    "Aquí podrás ver el estado de tus postulaciones y realizar tus entrevistas.",
  SELECT_APP_DESC: "Selecciona una postulación del menú para ver detalles.",
  NO_ACTIVE_APPS: "Aún no tienes postulaciones activas.",
  COMPLETE_PROFILE_SUCCESS: "¡Perfil Completado!",
  PROFILE_SAVED: "Tu información ha sido guardada correctamente.",
  SAVE_ERROR: "No se pudo guardar la información.",
  ONBOARDING_DESC: "Hola {name}, necesitamos un dato adicional para continuar.",
  NO_CANDIDATES: "No hay candidatos para tus vacantes aún.",
  NO_CANDIDATES_DESC:
    "Invita a candidatos para empezar el proceso de selección.",
  COMING_SOON_FEATURE: "Esta función estará disponible próximamente.",
  RESEND_FEATURE_DESC:
    "Esta función estará disponible próximamente para recordar a los candidatos.",
  JOB_NOT_FOUND: "Vacante no encontrada",
  NO_REQUIREMENTS: "No se especificaron requisitos.",
  COMPANY_SETUP_DESC:
    "Para continuar, necesitamos algunos detalles sobre tu organización.",
  COMPANY_CREATED_DESC:
    "Tu perfil de empresa ha sido configurado correctamente.",
  COMPANY_SAVE_ERROR: "No se pudo guardar la información de la empresa.",
  SAVING_INTERVIEW: "Guardando entrevista...",
  DO_NOT_CLOSE_WINDOW: "Por favor no cierres la ventana.",
  CONFIRM_LEAVE_INTERVIEW:
    "Tienes una entrevista en curso. Si sales ahora, perderás todo el progreso. ¿Estás seguro?",
  MIC_PERMISSION_REQUIRED: "Necesitas dar permiso al micrófono para continuar.",
  MIC_EXPLANATION:
    "Se solicitarán permisos de micrófono. La sesión será grabada.",
  CONNECTING_AGENT: "Conectando con Jennifer...",
  CONFIGURING_ENV: "Configurando entorno de entrevista seguro",
  FINISH_WARNING: "La entrevista finalizará y se guardará el registro.",
  CANNOT_START_INTERVIEW:
    "No es posible iniciar la entrevista en este momento.",
  INTERVIEW_COMPLETED_DESC:
    "Gracias por completar la entrevista. Tus respuestas han sido guardadas y serán revisadas pronto.",
  NO_APP_INFO: "No se encontró información de la aplicación.",
  LOADING_INTERVIEW: "Cargando Entrevista...",
  MIC_ERROR: "Ocurrió un error con el micrófono.",
  PROCESS_FINISHED_DESC:
    "Has completado esta etapa del proceso. La empresa revisará tus resultados.",
  INVITATION_DESC:
    "Has sido seleccionado para realizar una entrevista por voz con nuestro agente de IA.",
  INTERVIEW_ACTIVE_DESC:
    "Tu entrevista está activa. Puedes continuar donde la dejaste.",
  WAITING_DESC:
    "Tu solicitud ha sido enviada. Si tu perfil coincide, recibirás una invitación.",
  NO_TRANSCRIPT: "No hay transcripción disponible.",
  NO_TRANSCRIPT_AVAILABLE: "No hay transcripción disponible aún.",
  PDF_COMING_SOON: "La descarga de PDF estará disponible próximamente.",
  REPORT_ERROR: "No se pudo generar el informe de rendimiento.",
  REPORT_DESC: "Análisis detallado de la sesión de entrevista.",
  NO_JOBS_CREATED: "No hay vacantes creadas.",
  NO_RECENT_ACTIVITY: "No hay actividad reciente de candidatos.",
  TITLE_REQUIRED_HEADER: "⚠️ Título requerido",
  TITLE_REQUIRED_DESC: "Por favor ingresa el título del puesto.",
  TITLE_TOO_SHORT_HEADER: "⚠️ Título muy corto",
  TITLE_TOO_SHORT_DESC: "El título debe tener al menos 3 caracteres.",
  DESC_REQUIRED_HEADER: "⚠️ Descripción requerida",
  DESC_REQUIRED_DESC: "Por favor ingresa una descripción del puesto.",
  DESC_TOO_SHORT_HEADER: "⚠️ Descripción muy corta",
  DESC_TOO_SHORT_DESC: "La descripción debe tener al menos 50 caracteres.",
  TYPE_REQUIRED_HEADER: "⚠️ Tipo de contrato requerido",
  TYPE_REQUIRED_DESC: "Por favor selecciona un tipo de contrato.",
  MIN_SALARY_INVALID_HEADER: "⚠️ Salario mínimo inválido",
  MIN_SALARY_INVALID_DESC:
    "Por favor ingresa un salario mínimo válido mayor a 0.",
  SALARY_RANGE_INVALID_HEADER: "⚠️ Rango salarial inválido",
  SALARY_RANGE_INVALID_DESC:
    "El salario máximo debe ser mayor o igual al mínimo.",
  REQS_REQUIRED_HEADER: "⚠️ Requisitos requeridos",
  REQS_REQUIRED_DESC: "Por favor agrega al menos un requisito o skill.",
  ERROR_LOADING_JOBS: "No se pudieron cargar las vacantes disponibles.",
  CANDIDATE_NOT_FOUND_TITLE: "No encontrado",
  CANDIDATE_NOT_FOUND_DESC:
    "No se encontró un candidato con ese correo electrónico.",
  CANDIDATE_FOUND_TITLE: "Candidato encontrado",
  FIELDS_INCOMPLETE_TITLE: "Campos incompletos",
  FIELDS_INCOMPLETE_DESC: "Debes seleccionar una vacante.",
  EMAIL_REQUIRED_TITLE: "Email requerido",
  EMAIL_REQUIRED_DESC: "No se ha especificado un email.",
  ALREADY_INVITED_TITLE: "Ya invitado",
  ALREADY_INVITED_DESC:
    "Este candidato ya tiene una aplicación para esta vacante.",
  INVITATION_SENT_TITLE: "Invitación enviada",
  INVITATION_SENT_DESC: "El candidato ha sido notificado.",
  NOTICE_SENT_TITLE: "Aviso enviado",
  NOTICE_SENT_DESC: "El usuario ya existe, se le ha notificado.",
  INVITATION_SAVE_ERROR: "Error al guardar la invitación.",
  NEW_USER_INVITE_DESC: "Se ha enviado un correo de registro al nuevo usuario.",
  INVITE_DESC:
    "Asigna una vacante a un candidato para iniciar el proceso de entrevista.",
  ASSIGNMENT_SUCCESS_TITLE: "✅ Asignación exitosa",
  ASSIGNMENT_SUCCESS_DESC: "El candidato ha sido asignado a la vacante.",
  ASSIGNMENT_ERROR_TITLE: "Error en la asignación",
  SEARCH_ERROR_TITLE: "Error en la búsqueda",
  SEARCH_ERROR_DESC: "Ocurrió un error al buscar el candidato.",
  ALREADY_ASSIGNED_DESC: "El candidato ya está asignado a esta vacante.",
  FIELDS_REQUIRED_TITLE: "⚠️ Campos requeridos",
  FIELDS_REQUIRED_DESC:
    "Debes encontrar un candidato, seleccionar una vacante y estar autenticado.",
  PLACEHOLDER_DOC_NUMBER: "Introduce el número de documento...",
  PLACEHOLDER_SELECT_ACTIVE_JOB: "Selecciona una vacante activa...",
  NO_CANDIDATES_FOUND: "No se encontraron candidatos.",
  CANDIDATE_MUST_REGISTER:
    "El candidato debe estar registrado en la plataforma.",
  FORGOT_DESC_1:
    "Ingresa tu email y te enviaremos un enlace para recuperar tu cuenta.",
  FORGOT_INSTRUCTIONS: "Hemos enviado las instrucciones a",
  RESET_SUCCESS_DESC:
    "Revisa tu bandeja de entrada para restablecer tu contraseña.",
  SEND_RESET_ERROR: "No se pudo enviar el correo de recuperación.",
  RESET_SENT_TOAST: "Correo enviado",
  PASSWORD_UPDATED: "Tu contraseña ha sido actualizada. Redirigiendo...",
  PASSWORD_UPDATE_ERROR: "No se pudo actualizar la contraseña.",
  ENTER_NEW_PASSWORD: "Ingresa tu nueva contraseña segura.",
  WRONG_EMAIL: "Email incorrecto.",
  AUTH_ERROR_TITLE: "Error de autenticación",
  ADMIN_ACCESS_ONLY: "Acceso exclusivo para administradores.",
  ERROR_LOADING_COMPANIES: "No se pudieron cargar las empresas.",
  ERROR_DELETING_COMPANY: "No se pudo eliminar a la empresa.",
  COMPANY_DELETED: "Empresa eliminada.",
  DELETE_COMPANY_WARNING:
    "Esta acción es irreversible. Se eliminará permanentemente la empresa y todos sus datos asociados (vacantes, aplicaciones, etc.).",
  ERROR_LOADING_CANDIDATES: "No se pudieron cargar los candidatos.",
  ERROR_DELETING_CANDIDATE: "No se pudo eliminar al candidato.",
  CANDIDATE_DELETED: "Candidato eliminado.",
  DELETE_CANDIDATE_WARNING:
    "Esta acción es irreversible. Se eliminará permanentemente al candidato y todos sus datos asociados.",
  ERROR_LOADING_INTERVIEWS: "No se pudieron cargar las entrevistas.",
  EXPORT_NOT_IMPLEMENTED: "La exportación de datos aún no está implementada.",
  ADMIN_SETTINGS_DESC: "Gestiona los parámetros principales de la plataforma.",
  ERROR_LOADING_SETTINGS: "No se pudieron cargar los ajustes.",
  ERROR_SAVING_SETTINGS: "Algunos ajustes no se pudieron guardar.",
  SETTINGS_SAVED: "Todos los ajustes han sido guardados.",
  RETAIL_NOT_IMPLEMENTED:
    "La gestión de parámetros de retail aún no está implementada.",
  RETAIL_DESC:
    "Esta sección te permitirá configurar la apariencia y la funcionalidad de la interfaz de la tienda, como el nombre, logo, colores y claves de pasarelas de pago.",
  AI_QUESTIONS_DESC:
    "Estas preguntas serán usadas por el agente de IA durante la entrevista",
  FIELDS_INCOMPLETE_DESC_SIMPLE: "Por favor completa el título y descripción.",
  EMAIL_TEMPLATES_NOT_IMPLEMENTED:
    "La gestión de plantillas de email aún no está implementada.",
  EMAIL_TEMPLATES_DESC:
    "Aquí podrás editar el contenido de los correos de bienvenida, recuperación de contraseña, invitaciones a vacantes, y más.",
  CALL_TO_ACTION: "Convirtamos tus ideas en realidad.",
  INTERVIEW_START_WARNING:
    "⚠️ AVISO IMPORTANTE:\n\nUna vez que inicies la entrevista, no podrás pausarla ni reanudarla.\nSi sales de la página o finalizas la llamada antes de tiempo, tu postulación se marcará automáticamente como completada/finalizada.\n\n¿Estás listo para comenzar?",
  ERROR_UPDATING_JOB_DESC: "No se pudo actualizar la vacante: {error}",
  ERROR_DELETING_JOB_DESC: "No se pudo eliminar la vacante: {error}",
  APPLIED_TO: "aplicó para",
  STATUS_IN_REVIEW_DESC:
    "Tu entrevista ha finalizado. Estamos revisando tus resultados.",
  STATUS_IN_REVIEW_ALT_DESC:
    "Tu entrevista ha finalizado. El equipo está revisando tu perfil.",
  STATUS_APPROVED_DESC:
    "Has sido seleccionado para esta posición. Nos pondremos en contacto contigo pronto.",
  STATUS_REJECTED_DESC:
    "Gracias por tu interés, pero hemos decidido avanzar con otros candidatos.",
  PASSWORD_EMPTY_ERROR: "La contraseña no puede estar vacía.",
  CHANGE_PASSWORD_DESC: "Estás cambiando la contraseña para el usuario",
  CANDIDATE_FOUND_MSG: "está disponible para invitación.",
  INVITATION_SEND_ERROR: "No se pudo enviar la invitación.",
  LOADING_JOB_DETAILS: "Cargando detalles de la vacante...",
  ERROR_LOADING_JOB_TITLE: "No se pudo cargar el título de la vacante.",
  REQUESTING_MIC_PERMISSION: "Solicitando permiso de micrófono...",
  MIC_REFRESH_INSTRUCTION:
    "Por favor, actualiza los permisos del navegador y recarga la página.",
  SPEAK_TO_TEST: "Habla para probar tu micrófono",
  QUIET_PLACE_REQ: "Asegúrate de estar en un lugar tranquilo",
  CHECK_MIC_REQ: "Verifica que tu micrófono funciona correctamente",
  INTERVIEW_RECORDED: "La entrevista será grabada",
  WAITING_FOR_USER_SPEECH: "Esperando a que el usuario hable...",
  CAMERA_DISABLED: "La cámara está desactivada",
  AUDIO_DETECTED: "Audio detectado",
  RESEND_IN: "Reenviar en",
  ACCESS_DENIED_INTERVIEW: "Debes iniciar sesión para acceder a la entrevista.",
  GO_TO_LOGIN: "Ir al inicio",
  WELCOME_AI: "¡Hola! Soy",
  WELCOME_AI_SUBTITLE:
    "tu asistente de IA. Estoy aquí para ayudarte en tu proceso de selección.",
  APPROVE_CANDIDATE_WARNING:
    "Estás a punto de marcar a {name} como aprobado. Esto notificará al candidato.",
  REJECT_CANDIDATE_WARNING:
    "Estás a punto de rechazar la aplicación de {name}. Esta acción no se puede deshacer.",
  CONFIRM_APPROVE: "Confirmar Aprobación",
  CONFIRM_REJECT: "Confirmar Rechazo",
  NOT_LOGGED: "No registradas",
  PLAYBACK_SPEED: "Velocidad:",
  RESPONSES_COUNT: "{count} respuestas",
  MESSAGES_COUNT: "{count} mensajes",
  POSTULATED: "Postulado",
  IN_INTERVIEW: "En Entrevista",
  ANSWER: "Respuesta",
  APPLIED: "Aplicó",
  SEARCH_JOBS: "Buscar vacantes",
  STUB_COMPONENT_DESC: "Este componente no está en uso actualmente.",
  NOT_IMPLEMENTED_FEATURE: "Funcionalidad no implementada."
} as const;

export const TABS = {
  OVERVIEW: "overview",
  JOBS: "jobs",
  CANDIDATES: "candidates",
  SIGNIN: "signin",
  SIGNUP: "signup",
  ANALYTICS: "analytics"
} as const;

export const TAB_LABELS = {
  OVERVIEW: "Resumen",
  JOBS: "Vacantes",
  CANDIDATES: "Candidatos",
  ANALYTICS: "Analíticas"
} as const;

export const PLACEHOLDERS = {
  EMAIL_GENERIC: "tu@email.com",
  FULL_NAME: "Tu Nombre Completo",
  LAST_NAME: "Tu Apellido",
  JOB_TITLE: "ej: Desarrollador Full Stack Senior",
  LOCATION: "ej: Remoto, Madrid, etc.",
  DESCRIPTION: "Describe el puesto, responsabilidades y lo que buscas...",
  SALARY_MIN: "50000",
  SALARY_MAX: "70000",
  SKILLS: "ej: React, TypeScript, Node.js (presiona Enter)",
  NAME_NOT_AVAILABLE: "Nombre no disponible",
  EMAIL_NOT_AVAILABLE: "Email no disponible",
  DOC_NUMBER_PH: "Tu número de identidad",
  UNSPECIFIED: "No especificado",
  NEGOTIABLE: "A convenir",
  COMPANY_NAME_PH: "Ej. Tech Solutions Inc.",
  COMPANY_DESC_PH: "Cuéntanos brevemente qué hace tu empresa...",
  PHONE_PH: "+52 555...",
  SEARCH_BY_EMAIL: "Buscar por email...",
  SELECT_JOB: "Seleccionar vacante",
  SEARCH_NAME_EMAIL: "Buscar por nombre o email...",
  ADMIN_SEARCH_USERS: "Buscar por nombre, email o empresa...",
  FILTER_BY_STATUS: "Filtrar por estado (ej: completed)...",
  QUESTION_EXAMPLE: "ej: ¿Cuál es tu experiencia con TypeScript?",
  ENTER_NEW_PASSWORD_PH: "Ingresa la nueva contraseña",
  GENERIC_CANDIDATE: "Candidato",
  GENERIC_VACANCY: "la vacante"
} as const;

export const LABELS = {
  EMAIL: "Email",
  PASSWORD: "Contraseña",
  NEW_PASSWORD: "Nueva Contraseña",
  FULL_NAME: "Nombre Completo",
  LAST_NAME: "Apellido",
  CONFIRM_PASSWORD: "Confirmar Contraseña",
  JOB_TITLE: "Título",
  LOCATION: "Ubicación",
  CONTRACT_TYPE: "Tipo de contrato",
  STATUS: "Estado",
  DESCRIPTION: "Descripción",
  SALARY_MIN: "Salario mínimo",
  SALARY_MAX: "Salario máximo",
  CURRENCY: "Moneda",
  REQUIREMENTS: "Requisitos (Skills)",
  AI_QUESTIONS: "Preguntas para la IA",
  ACTIVE_JOBS: "Vacantes Activas",
  TOTAL_CANDIDATES: "Candidatos Totales",
  TOTAL_INTERVIEWS: "Total Entrevistas",
  PENDING_INTERVIEWS: "Entrevistas Pendientes",
  ACTION_REQUIRED: "Acción Requerida",
  DOCUMENT_NUMBER: "Número de Documento",
  APPLIED_DATE: "Aplicado",
  DOC_SHORT: "Doc",
  COMPANY_NAME: "Nombre de la Empresa",
  PHONE: "Teléfono",
  CONTACT_EMAIL: "Email de Contacto",
  CURRENT_STATUS: "Estado actual",
  INTERVIEW_IN_PROGRESS: "Entrevista en curso",
  READY: "Listo",
  FINISHED: "Finalizado",
  UNKNOWN: "Desconocido",
  COMPLETED_BADGE: "Completado",
  PENDING_BADGE: "Pendiente",
  IN_COURSE_BADGE: "En Curso",
  ANSWER_QUALITY: "Calidad de Respuesta",
  ENGAGEMENT: "Engagement",
  CLARITY: "Claridad",
  TECH_PROFICIENCY: "Competencia Técnica",
  RESPONSE_TIME: "Tiempo de Resp.",
  OVERALL_SENTIMENT: "Sentimiento General",
  OVERALL_SCORE: "Puntuación General",
  OUT_OF_100: "sobre 100",
  ACTIVE_JOB: "Activa",
  INACTIVE_JOB: "Inactiva",
  CANDIDATE: "Candidato",
  SELECTED: "Seleccionado",
  FOUND: "Encontrado",
  JOB: "Vacante",
  APPLICANT: "aplicante",
  APPLICANTS: "aplicantes",
  SEARCH_REGISTERED_CANDIDATE: "Buscar Candidato Registrado",
  TOTAL_USERS: "Total de Usuarios",
  COMPANIES: "Empresas",
  CANDIDATES: "Candidatos",
  JOBS_CREATED: "Vacantes Creadas",
  APPLICATIONS: "Aplicaciones",
  USER: "Usuario",
  ROLE: "Rol",
  REGISTERED_DATE: "Fecha de Registro",
  ACTIONS: "Acciones",
  COMPANY: "Empresa",
  INTERVIEWS: "Entrevistas",
  LAST_STATUS: "Último Estado",
  REGISTERED: "Registro",
  DATE: "Fecha",
  PAGE: "Página",
  OF: "de",
  SALARY_RANGE: "Rango salarial",
  POSITIVE: "Positivo",
  NEUTRAL: "Neutral",
  NEGATIVE: "Negativo",
  ANALYZING: "Analizando...",
  QUALITY_EXCELLENT: "Excelente",
  QUALITY_GOOD: "Buena",
  QUALITY_FAIR: "Regular",
  QUALITY_POOR: "Mala",
  ENABLED: "Activada",
  DISABLED: "Desactivada",
  RECORDING_STATUS: "Grabando",
  STOPPED_STATUS: "Detenida",
  SELECT_MIC: "Seleccionar Micrófono",
  MICROPHONE: "Micrófono",
  AUDIO_LEVEL: "Nivel de Audio",
  BEFORE_CONTINUE: "Antes de continuar:",
  POSITION: "Posición",
  DEPARTMENT: "Departamento",
  FILTER_BY: "Filtrar por:",
  AVERAGE: "Promedio",
  ANSWER_QUALITY_SHORT: "Calidad Resp.",
  COMMUNICATION_SHORT: "Comunicación",
  TECH_SHORT: "Técnica",
  NETWORK_LATENCY: "Latencia de Red",
  CONNECTION_QUALITY: "Calidad de Conexión",
  CAMERA: "Cámara",
  RECORDING: "Grabación",
  READY_TO_START: "Listo para iniciar",
  CONNECTING: "Conectando...",
  CONNECTED: "Conectado",
  INTERVIEW_FINISHED: "Entrevista finalizada",
  CONNECTION_ERROR: "Error en la conexión",
  SPEAKING: "Hablando...",
  WAITING: "Esperando...",
  LOCALE_ES: "es-ES",
  NOT_AVAILABLE: "N/A",
  IN_REVIEW: "En Revisión",
  HIRED: "Contratado",
  NOT_SELECTED: "No Seleccionado",
  DURATION: "Duración",
  INTERACTION: "Interacción",
  TECH_SCORE: "Puntaje Técnico",
  AI_DECISION: "Decisión IA",
  PENDING: "Pendiente",
  VACANCY: "Vacante",
  REJECT: "Rechazar",
  APPROVE_HIRE: "Aprobar Contratación",
  POSTULATED: "Postulado",
  IN_INTERVIEW: "En Entrevista",
  ANSWER: "Respuesta",
  APPLIED: "Aplicó",
  COMPLETED: "Completada"
} as const;

export const DEBUG = {
  INTEGRATION_TEST: "🧪 Prueba de Integración",
  STATUS_INVITED_IN_PROGRESS: "Estado: Invitado/En Proceso",
  CAN_INTERVIEW: "Puede Entrevistar",
  CALL_CONNECTED: "Llamada Conectada",
  AUDIO_DETECTED: "Audio Detectado",
  CONVERSATION_ACTIVE: "Conversación Activa",
  INTERVIEW_ENDED: "Entrevista Finalizada",
  STATUS_COMPLETED: "Estado: Completado",
  STATUS: "Estado",
  CALL: "Llamada",
  AUDIO: "Audio",
  MSGS: "Msgs"
} as const;

export const LINKS = {
  FORGOT_PASSWORD: "¿Olvidaste tu contraseña?"
} as const;

export const EMAILS = {
  TYPES: {
    VERIFICATION: "verification",
    INVITATION_NEW: "invitation_new",
    INVITATION_EXISTING: "invitation_existing",
    RESET_PASSWORD: "reset_password",
    INTERVIEW_COMPLETED: "notification_completed",
    INVITATION_ACCEPTED: "notification_invite_accepted",
    DECISION_APPROVED: "decision_approved",
    DECISION_REJECTED: "decision_rejected"
  },
  SUBJECTS: {
    VERIFICATION: "Verifica tu correo - Conecta",
    INVITATION_NEW: "Invitación a unirse a Conecta",
    INVITATION_EXISTING: "Nueva invitación en Conecta",
    RESET_PASSWORD: "Restablecer contraseña",
    INTERVIEW_COMPLETED: "Entrevista Completada",
    INVITATION_ACCEPTED: "¡Candidato ha aceptado la invitación!",
    DECISION_APPROVED: "¡Felicidades! Has sido seleccionado para {jobTitle}",
    DECISION_REJECTED: "Actualización sobre tu aplicación para {jobTitle}"
  },
  TEMPLATES: {
    HELLO: "Hola {name},",
    THANKS_PARTICIPATION:
      "Gracias por tu interés en la posición de <strong>{jobTitle}</strong> y por tomarte el tiempo para completar nuestro proceso de entrevista con IA.",
    SELECT_SUCCESS:
      "Nos complace informarte que has sido seleccionado para avanzar a la siguiente etapa o ser contratado para la posición de <strong>{jobTitle}</strong> en Conecta.",
    REJECTION_REASON:
      "Después de revisar tu perfil y los resultados de la entrevista, hemos decidido no avanzar contigo en este proceso de selección por el momento.",
    FUTURE_OPPORTUNITIES:
      "Te agradecemos mucho tu participación y mantendremos tu perfil en nuestra base de talento para futuras oportunidades que se alineen mejor con tus habilidades.",
    GOOD_LUCK: "Te deseamos mucho éxito en tu búsqueda laboral.",
    TEAM_SIGNATURE: "El equipo de Conecta",
    BEST_REGARDS: "Atentamente,",
    WELCOME_TITLE: "¡Buenas noticias, {name}!",
    HR_CONTACT:
      "Nuestro equipo de Recursos Humanos se pondrá en contacto contigo muy pronto para discutir los siguientes pasos y detalles de tu incorporación.",
    WELCOME_ABOARD: "¡Bienvenido a bordo!",
    UPDATE_TITLE: "Actualización sobre tu aplicación",
    WELCOME_TO_CONECTA: "Bienvenido a Conecta",
    THANKS_SIGNUP:
      "Gracias por registrarte. Para completar tu cuenta y acceder a la plataforma, por favor verifica tu correo electrónico haciendo clic en el siguiente botón:",
    VERIFY_BUTTON: "Verificar mi correo",
    IGNORE_IF_NOT_YOU:
      "Si no solicitaste esta cuenta, puedes ignorar este correo.",
    HAS_BEEN_INVITED: "Has sido invitado a Conecta",
    INVITE_ROLE:
      "Se te ha invitado a unirte a Conecta como <strong>{role}</strong>.",
    ACCEPT_INVITE:
      "Para aceptar la invitación y crear tu cuenta, haz clic en el siguiente botón:",
    JOIN_BUTTON: "Unirme a Conecta",
    EXPIRATION_NOTICE: "El enlace expirará en 7 días.",
    NEW_INVITE_CONECTA: "Nueva invitación en Conecta",
    EXISTING_USER_INVITE:
      "Te han invitado a una nueva posición en Conecta. Como ya tienes una cuenta, puedes acceder directamente para ver los detalles.",
    GO_TO_DASHBOARD: "Ir a mi Dashboard",
    RESET_PW_TITLE: "Restablecer Contraseña",
    RESET_PW_DESC:
      "Recibimos una solicitud para restablecer tu contraseña en Conecta.",
    RESET_BUTTON: "Restablecer Contraseña",
    RESET_IGNORE:
      "Si no solicitaste esto, ignora este correo. Tu contraseña permanecerá segura.",
    INTERVIEW_COMPLETED_TITLE: "Entrevista Completada",
    INTERVIEW_COMPLETED_DESC:
      "La entrevista con <strong>{name}</strong> ha sido completada exitosamente.",
    DATE: "Fecha: {date}",
    REVIEW_RESULTS:
      "Puedes revisar los resultados y la transcripción en tu panel de control.",
    VIEW_RESULTS_BUTTON: "Ver Resultados",
    INVITE_ACCEPTED_TITLE: "¡Invitación Aceptada!",
    INVITE_ACCEPTED_DESC:
      "El candidato <strong>{email}</strong> ha aceptado tu invitación para la posición de <strong>{jobTitle}</strong> en <strong>{companyName}</strong>.",
    READY_TO_CONTINUE:
      "El candidato ha sido añadido a tu lista de aplicaciones y está listo para continuar con el proceso de selección.",
    VIEW_CANDIDATE_BUTTON: "Ver Candidato"
  }
} as const;
