-- Migration to support storing detailed interview analysis

BEGIN;

-- 1. Create interview_responses table if not exists
CREATE TABLE IF NOT EXISTS interview_responses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES applications(id) ON DELETE CASCADE NOT NULL,
  question_id BIGINT REFERENCES listing_questions(id) ON DELETE SET NULL, -- Nullable if general question or unmatched
  question_text TEXT,
  response TEXT NOT NULL,
  score INTEGER, -- Optional score per question
  quality TEXT, -- Optional quality (Poor/Good etc)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS
ALTER TABLE interview_responses ENABLE ROW LEVEL SECURITY;

-- Policy for Service Role (Admin)
CREATE POLICY "Service Role can do anything on interview_responses" ON interview_responses
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Drop existing policies if needed to avoid conflicts
DROP POLICY IF EXISTS "Companies can view responses for their apps" ON interview_responses;
DROP POLICY IF EXISTS "Candidates can view their own responses" ON interview_responses;

-- Policy for Companies (Read Only)
CREATE POLICY "Companies can view responses for their apps" ON interview_responses
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM applications a
      JOIN listings l ON a.listing_id = l.id
      JOIN users u ON l.company_id = u.company_id
      WHERE a.id = interview_responses.application_id
      AND u.auth_user_id = auth.uid()
    )
  );

-- Policy for Candidates (Read Only - their own)
CREATE POLICY "Candidates can view their own responses" ON interview_responses
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM applications a
      WHERE a.id = interview_responses.application_id
      AND a.user_id = (SELECT id FROM users WHERE auth_user_id = auth.uid())
    )
  );
  
-- Grant permissions
GRANT SELECT ON interview_responses TO authenticated;
GRANT ALL ON interview_responses TO service_role;
GRANT ALL ON interview_responses TO postgres; 
GRANT ALL ON interview_responses TO anon; -- Granting anon for read? Maybe not needed.

-- 2. Add technical_competency_score to applications
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'applications' AND column_name = 'technical_competency_score') THEN
        ALTER TABLE applications ADD COLUMN technical_competency_score INTEGER;
    END IF;
END $$;

-- 3. Add json_data to reports
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reports' AND column_name = 'json_data') THEN
        ALTER TABLE reports ADD COLUMN json_data JSONB;
    END IF;
END $$;

COMMIT;
